---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  KC_DB_PASSWORD: {{ .Values.secrets.keycloakDbPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_ADMIN:          {{ .Values.secrets.keycloakAdmin }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  USER_DB_PASSWORD: {{ .Values.secrets.userDbPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  PRODUCT_DB_PASSWORD: {{ .Values.secrets.productDbPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  ORDER_DB_PASSWORD: {{ .Values.secrets.orderDbPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: order-client-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  ORDER_SERVICE_CLIENT_SECRET: {{ .Values.secrets.orderClientSecret }}

---
apiVersion: v1
kind: Secret
metadata:
  name: config-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  CONFIG_SERVER_PASSWORD: {{ .Values.secrets.configServerPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword }}
