---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-keycloak-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.postgresKeycloak }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-user-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.postgresUser }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-product-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.postgresProduct }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.postgresOrder }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.prometheus }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.loki }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.tempo }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.sizes.grafana }}
