# IMPORTANT: Change all values before deploying to a real cluster.
# stringData is base64-encoded automatically by Kubernetes.

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: myapp
type: Opaque
stringData:
  KC_DB_PASSWORD: "keycloak_db_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: myapp
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "Admin@1234!"

---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: myapp
type: Opaque
stringData:
  USER_DB_PASSWORD: "user_db_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
  namespace: myapp
type: Opaque
stringData:
  PRODUCT_DB_PASSWORD: "product_db_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: config-server-secret
  namespace: myapp
type: Opaque
stringData:
  CONFIG_SERVER_PASSWORD: "config_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: myapp
type: Opaque
stringData:
  ORDER_DB_PASSWORD: "order_db_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: order-client-secret
  namespace: myapp
type: Opaque
stringData:
  ORDER_SERVICE_CLIENT_SECRET: "order-service-secret"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: myapp
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "grafana_pass"
