---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.tempo }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" (dict "component" "tempo" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" (dict "component" "tempo" "root" .) | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsNonRoot: true
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
            - name: tempo-data
              mountPath: /var/tempo
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources.tempo | nindent 12 }}
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "myapp.selectorLabels" (dict "component" "tempo" "root" .) | nindent 4 }}
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
